wandb_version: 1

architecture:
  desc: null
  value: GCNN
dataset:
  desc: null
  value: MP-bandgaps-27-09-2024
epochs:
  desc: null
  value: 100
batch_size:
  desc: null
  value: 128
learning_rate:
  desc: null
  value: 0.001
dropout:
  desc: null
  value: 0.1
_wandb:
  desc: null
  value:
    python_version: 3.10.12
    cli_version: 0.16.2
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1728045822.517924
    t:
      1:
      - 1
      - 55
      - 77
      2:
      - 1
      - 55
      - 77
      3:
      - 16
      - 23
      4: 3.10.12
      5: 0.16.2
      8:
      - 1
      - 5
      13: linux-x86_64
